name: api
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  freezed_annotation: ^2.4.1
  injectable: ^2.4.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

  
dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  lints: ^3.0.0
  mews_pedantic: ^0.26.0
  retrofit_generator: ^8.1.0
  test: ^1.24.0
